# Generated by Django 5.2.5 on 2025-09-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('fiat', 'Fiat'), ('byd', 'BYD'), ('chevrolet', 'Chevrolet')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_brand', to='cars.brand'),
        ),
    ]
