# Generated by Django 5.2.5 on 2025-09-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_cars_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('byd', 'BYD'), ('chevrolet', 'Chevrolet')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
