# Generated by Django 5.2.5 on 2025-09-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_brand_cars_photos_alter_cars_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
