# Generated by Django 5.2.5 on 2025-09-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ImageField(blank=True, default='cars/sem_imagem.png', null=True, upload_to='cars/'),
        ),
    ]
